namespace CinemaPro.WinForms.DesignFirst.Forms.Admin;

partial class MovieManagementForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel filterPanel = null!;
    private TextBox searchTextBox = null!;
    private ComboBox genreComboBox = null!;
    private ComboBox statusComboBox = null!;
    private Button addButton = null!;
    private Button editButton = null!;
    private Button deleteButton = null!;
    private Button refreshButton = null!;
    private Panel gridPanel = null!;
    private DataGridView movieGrid = null!;
    private Panel detailPanel = null!;
    private TextBox titleTextBox = null!;
    private TextBox directorTextBox = null!;
    private TextBox durationTextBox = null!;
    private ComboBox ageComboBox = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        filterPanel = new Panel();
        searchTextBox = new TextBox();
        genreComboBox = new ComboBox();
        statusComboBox = new ComboBox();
        addButton = new Button();
        editButton = new Button();
        deleteButton = new Button();
        refreshButton = new Button();
        gridPanel = new Panel();
        movieGrid = new DataGridView();
        detailPanel = new Panel();
        titleTextBox = new TextBox();
        directorTextBox = new TextBox();
        durationTextBox = new TextBox();
        ageComboBox = new ComboBox();
        var detailTitleLabel = new Label();
        var posterBox = new Panel();
        var posterLabel = new Label();
        var titleLabel = new Label();
        var directorLabel = new Label();
        var durationLabel = new Label();
        var ageLabel = new Label();
        var listTitleLabel = new Label();
        filterPanel.SuspendLayout();
        gridPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)movieGrid).BeginInit();
        detailPanel.SuspendLayout();
        posterBox.SuspendLayout();
        SuspendLayout();
        filterPanel.BackColor = Color.White;
        filterPanel.BorderStyle = BorderStyle.FixedSingle;
        filterPanel.Controls.Add(refreshButton);
        filterPanel.Controls.Add(deleteButton);
        filterPanel.Controls.Add(editButton);
        filterPanel.Controls.Add(addButton);
        filterPanel.Controls.Add(statusComboBox);
        filterPanel.Controls.Add(genreComboBox);
        filterPanel.Controls.Add(searchTextBox);
        filterPanel.Location = new Point(18, 14);
        filterPanel.Size = new Size(1048, 64);
        searchTextBox.Font = new Font("Segoe UI", 10F);
        searchTextBox.Location = new Point(18, 20);
        searchTextBox.PlaceholderText = "Tìm kiếm phim...";
        searchTextBox.Size = new Size(260, 25);
        genreComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        genreComboBox.Font = new Font("Segoe UI", 9.5F);
        genreComboBox.Items.AddRange(new object[] { "Tất cả thể loại", "Hành động", "Tâm lý", "Hoạt hình" });
        genreComboBox.Location = new Point(298, 20);
        genreComboBox.Size = new Size(150, 25);
        statusComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        statusComboBox.Font = new Font("Segoe UI", 9.5F);
        statusComboBox.Items.AddRange(new object[] { "Tất cả trạng thái", "Đang chiếu", "Sắp chiếu", "Ngừng chiếu" });
        statusComboBox.Location = new Point(464, 20);
        statusComboBox.Size = new Size(160, 25);
        addButton.BackColor = Color.FromArgb(37, 99, 235);
        addButton.FlatAppearance.BorderSize = 0;
        addButton.FlatStyle = FlatStyle.Flat;
        addButton.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        addButton.ForeColor = Color.White;
        addButton.Location = new Point(646, 16);
        addButton.Size = new Size(88, 34);
        addButton.Text = "Thêm";
        addButton.Click += ActionButton_Click;
        editButton.BackColor = Color.White;
        editButton.FlatStyle = FlatStyle.Flat;
        editButton.Location = new Point(744, 16);
        editButton.Size = new Size(88, 34);
        editButton.Text = "Sửa";
        editButton.Click += ActionButton_Click;
        deleteButton.BackColor = Color.White;
        deleteButton.FlatStyle = FlatStyle.Flat;
        deleteButton.ForeColor = Color.FromArgb(220, 38, 38);
        deleteButton.Location = new Point(842, 16);
        deleteButton.Size = new Size(98, 34);
        deleteButton.Text = "Ngừng chiếu";
        deleteButton.Click += ActionButton_Click;
        refreshButton.BackColor = Color.White;
        refreshButton.FlatStyle = FlatStyle.Flat;
        refreshButton.Location = new Point(950, 16);
        refreshButton.Size = new Size(80, 34);
        refreshButton.Text = "Làm mới";
        refreshButton.Click += RefreshButton_Click;
        gridPanel.BackColor = Color.White;
        gridPanel.BorderStyle = BorderStyle.FixedSingle;
        gridPanel.Controls.Add(movieGrid);
        gridPanel.Controls.Add(listTitleLabel);
        gridPanel.Location = new Point(18, 94);
        gridPanel.Size = new Size(690, 496);
        listTitleLabel.AutoSize = true;
        listTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        listTitleLabel.Location = new Point(18, 18);
        listTitleLabel.Text = "Danh sách phim";
        movieGrid.AllowUserToAddRows = false;
        movieGrid.AllowUserToDeleteRows = false;
        movieGrid.BackgroundColor = Color.White;
        movieGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        movieGrid.Columns.Add("colMovieId", "Mã phim");
        movieGrid.Columns.Add("colTitle", "Tên phim");
        movieGrid.Columns.Add("colGenre", "Thể loại");
        movieGrid.Columns.Add("colDuration", "Thời lượng");
        movieGrid.Columns.Add("colAge", "Độ tuổi");
        movieGrid.Columns.Add("colDirector", "Đạo diễn");
        movieGrid.Columns.Add("colStatus", "Trạng thái");
        movieGrid.Location = new Point(18, 56);
        movieGrid.ReadOnly = true;
        movieGrid.RowHeadersVisible = false;
        movieGrid.Size = new Size(652, 420);
        movieGrid.Rows.Add("MV001", "Avengers: Endgame", "Hành động", "182 phút", "C13", "Anthony Russo", "Đang chiếu");
        detailPanel.BackColor = Color.White;
        detailPanel.BorderStyle = BorderStyle.FixedSingle;
        detailPanel.Controls.Add(ageLabel);
        detailPanel.Controls.Add(ageComboBox);
        detailPanel.Controls.Add(durationLabel);
        detailPanel.Controls.Add(durationTextBox);
        detailPanel.Controls.Add(directorLabel);
        detailPanel.Controls.Add(directorTextBox);
        detailPanel.Controls.Add(titleLabel);
        detailPanel.Controls.Add(titleTextBox);
        detailPanel.Controls.Add(posterBox);
        detailPanel.Controls.Add(detailTitleLabel);
        detailPanel.Location = new Point(724, 94);
        detailPanel.Size = new Size(342, 496);
        detailTitleLabel.AutoSize = true;
        detailTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        detailTitleLabel.Location = new Point(18, 18);
        detailTitleLabel.Text = "Thông tin phim";
        posterBox.BackColor = Color.FromArgb(15, 23, 42);
        posterBox.Controls.Add(posterLabel);
        posterBox.Location = new Point(22, 56);
        posterBox.Size = new Size(150, 104);
        posterLabel.Dock = DockStyle.Fill;
        posterLabel.ForeColor = Color.White;
        posterLabel.Text = "Poster";
        posterLabel.TextAlign = ContentAlignment.MiddleCenter;
        titleLabel.AutoSize = true;
        titleLabel.Location = new Point(22, 184);
        titleLabel.Text = "Tên phim";
        titleTextBox.Location = new Point(22, 206);
        titleTextBox.Size = new Size(290, 23);
        titleTextBox.Text = "Avengers: Endgame";
        directorLabel.AutoSize = true;
        directorLabel.Location = new Point(22, 244);
        directorLabel.Text = "Đạo diễn";
        directorTextBox.Location = new Point(22, 266);
        directorTextBox.Size = new Size(290, 23);
        directorTextBox.Text = "Anthony Russo";
        durationLabel.AutoSize = true;
        durationLabel.Location = new Point(22, 304);
        durationLabel.Text = "Thời lượng";
        durationTextBox.Location = new Point(22, 326);
        durationTextBox.Size = new Size(138, 23);
        durationTextBox.Text = "182";
        ageLabel.AutoSize = true;
        ageLabel.Location = new Point(174, 304);
        ageLabel.Text = "Độ tuổi";
        ageComboBox.Items.AddRange(new object[] { "P", "C13", "C16", "C18" });
        ageComboBox.Location = new Point(174, 326);
        ageComboBox.Size = new Size(138, 23);
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(detailPanel);
        Controls.Add(gridPanel);
        Controls.Add(filterPanel);
        Name = "MovieManagementForm";
        Text = "Quản lý phim";
        Load += MovieManagementForm_Load;
        filterPanel.ResumeLayout(false);
        filterPanel.PerformLayout();
        gridPanel.ResumeLayout(false);
        gridPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)movieGrid).EndInit();
        detailPanel.ResumeLayout(false);
        detailPanel.PerformLayout();
        posterBox.ResumeLayout(false);
        ResumeLayout(false);
    }
}
