namespace CinemaPro.WinForms.DesignFirst.Forms.Admin;

partial class RevenueReportForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel actionPanel = null!;
    private DateTimePicker reportDatePicker = null!;
    private Button viewReportButton = null!;
    private Button exportButton = null!;
    private Panel todayRevenuePanel = null!;
    private Label todayRevenueTitleLabel = null!;
    private Label todayRevenueValueLabel = null!;
    private Panel totalTicketPanel = null!;
    private Label totalTicketTitleLabel = null!;
    private Label totalTicketValueLabel = null!;
    private Panel topMoviePanel = null!;
    private Label topMovieTitleLabel = null!;
    private Label topMovieValueLabel = null!;
    private Panel bestShowtimePanel = null!;
    private Label bestShowtimeTitleLabel = null!;
    private Label bestShowtimeValueLabel = null!;
    private Panel gridPanel = null!;
    private Label gridTitleLabel = null!;
    private DataGridView revenueGrid = null!;
    private DataGridViewTextBoxColumn colDate = null!;
    private DataGridViewTextBoxColumn colMovie = null!;
    private DataGridViewTextBoxColumn colTickets = null!;
    private DataGridViewTextBoxColumn colRevenue = null!;
    private DataGridViewTextBoxColumn colPayment = null!;
    private Panel chartPanel = null!;
    private Label chartTitleLabel = null!;
    private Label barMaiLabel = null!;
    private Label barDuneLabel = null!;
    private Label barAvengersLabel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        actionPanel = new Panel();
        exportButton = new Button();
        viewReportButton = new Button();
        reportDatePicker = new DateTimePicker();
        todayRevenuePanel = new Panel();
        todayRevenueValueLabel = new Label();
        todayRevenueTitleLabel = new Label();
        totalTicketPanel = new Panel();
        totalTicketValueLabel = new Label();
        totalTicketTitleLabel = new Label();
        topMoviePanel = new Panel();
        topMovieValueLabel = new Label();
        topMovieTitleLabel = new Label();
        bestShowtimePanel = new Panel();
        bestShowtimeValueLabel = new Label();
        bestShowtimeTitleLabel = new Label();
        gridPanel = new Panel();
        revenueGrid = new DataGridView();
        colDate = new DataGridViewTextBoxColumn();
        colMovie = new DataGridViewTextBoxColumn();
        colTickets = new DataGridViewTextBoxColumn();
        colRevenue = new DataGridViewTextBoxColumn();
        colPayment = new DataGridViewTextBoxColumn();
        gridTitleLabel = new Label();
        chartPanel = new Panel();
        barAvengersLabel = new Label();
        barDuneLabel = new Label();
        barMaiLabel = new Label();
        chartTitleLabel = new Label();
        actionPanel.SuspendLayout();
        todayRevenuePanel.SuspendLayout();
        totalTicketPanel.SuspendLayout();
        topMoviePanel.SuspendLayout();
        bestShowtimePanel.SuspendLayout();
        gridPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)revenueGrid).BeginInit();
        chartPanel.SuspendLayout();
        SuspendLayout();
        // 
        // actionPanel
        // 
        actionPanel.BackColor = Color.White;
        actionPanel.BorderStyle = BorderStyle.FixedSingle;
        actionPanel.Controls.Add(exportButton);
        actionPanel.Controls.Add(viewReportButton);
        actionPanel.Controls.Add(reportDatePicker);
        actionPanel.Location = new Point(18, 14);
        actionPanel.Name = "actionPanel";
        actionPanel.Size = new Size(1048, 58);
        actionPanel.TabIndex = 0;
        reportDatePicker.Font = new Font("Segoe UI", 9.5F);
        reportDatePicker.Format = DateTimePickerFormat.Short;
        reportDatePicker.Location = new Point(18, 17);
        reportDatePicker.Name = "reportDatePicker";
        reportDatePicker.Size = new Size(140, 24);
        reportDatePicker.TabIndex = 0;
        viewReportButton.BackColor = Color.FromArgb(37, 99, 235);
        viewReportButton.FlatAppearance.BorderSize = 0;
        viewReportButton.FlatStyle = FlatStyle.Flat;
        viewReportButton.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        viewReportButton.ForeColor = Color.White;
        viewReportButton.Location = new Point(178, 13);
        viewReportButton.Name = "viewReportButton";
        viewReportButton.Size = new Size(124, 32);
        viewReportButton.TabIndex = 1;
        viewReportButton.Text = "Xem báo cáo";
        viewReportButton.UseVisualStyleBackColor = false;
        viewReportButton.Click += ViewReportButton_Click;
        exportButton.BackColor = Color.White;
        exportButton.FlatStyle = FlatStyle.Flat;
        exportButton.Font = new Font("Segoe UI", 9.5F);
        exportButton.ForeColor = Color.FromArgb(17, 24, 39);
        exportButton.Location = new Point(318, 13);
        exportButton.Name = "exportButton";
        exportButton.Size = new Size(124, 32);
        exportButton.TabIndex = 2;
        exportButton.Text = "Xuất báo cáo";
        exportButton.UseVisualStyleBackColor = false;
        exportButton.Click += ExportButton_Click;
        // 
        // stat panels
        // 
        todayRevenuePanel.BackColor = Color.White;
        todayRevenuePanel.BorderStyle = BorderStyle.FixedSingle;
        todayRevenuePanel.Controls.Add(todayRevenueValueLabel);
        todayRevenuePanel.Controls.Add(todayRevenueTitleLabel);
        todayRevenuePanel.Location = new Point(18, 88);
        todayRevenuePanel.Name = "todayRevenuePanel";
        todayRevenuePanel.Size = new Size(250, 92);
        todayRevenuePanel.TabIndex = 1;
        todayRevenueTitleLabel.Font = new Font("Segoe UI", 9.5F);
        todayRevenueTitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
        todayRevenueTitleLabel.Location = new Point(18, 16);
        todayRevenueTitleLabel.Name = "todayRevenueTitleLabel";
        todayRevenueTitleLabel.Size = new Size(190, 20);
        todayRevenueTitleLabel.TabIndex = 0;
        todayRevenueTitleLabel.Text = "Doanh thu hôm nay";
        todayRevenueValueLabel.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
        todayRevenueValueLabel.ForeColor = Color.FromArgb(37, 99, 235);
        todayRevenueValueLabel.Location = new Point(18, 42);
        todayRevenueValueLabel.Name = "todayRevenueValueLabel";
        todayRevenueValueLabel.Size = new Size(210, 34);
        todayRevenueValueLabel.TabIndex = 1;
        todayRevenueValueLabel.Text = "585.000 đ";
        totalTicketPanel.BackColor = Color.White;
        totalTicketPanel.BorderStyle = BorderStyle.FixedSingle;
        totalTicketPanel.Controls.Add(totalTicketValueLabel);
        totalTicketPanel.Controls.Add(totalTicketTitleLabel);
        totalTicketPanel.Location = new Point(284, 88);
        totalTicketPanel.Name = "totalTicketPanel";
        totalTicketPanel.Size = new Size(250, 92);
        totalTicketPanel.TabIndex = 2;
        totalTicketTitleLabel.Font = new Font("Segoe UI", 9.5F);
        totalTicketTitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
        totalTicketTitleLabel.Location = new Point(18, 16);
        totalTicketTitleLabel.Name = "totalTicketTitleLabel";
        totalTicketTitleLabel.Size = new Size(190, 20);
        totalTicketTitleLabel.TabIndex = 0;
        totalTicketTitleLabel.Text = "Tổng vé đã bán";
        totalTicketValueLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        totalTicketValueLabel.ForeColor = Color.FromArgb(22, 163, 74);
        totalTicketValueLabel.Location = new Point(18, 36);
        totalTicketValueLabel.Name = "totalTicketValueLabel";
        totalTicketValueLabel.Size = new Size(120, 42);
        totalTicketValueLabel.TabIndex = 1;
        totalTicketValueLabel.Text = "4";
        topMoviePanel.BackColor = Color.White;
        topMoviePanel.BorderStyle = BorderStyle.FixedSingle;
        topMoviePanel.Controls.Add(topMovieValueLabel);
        topMoviePanel.Controls.Add(topMovieTitleLabel);
        topMoviePanel.Location = new Point(550, 88);
        topMoviePanel.Name = "topMoviePanel";
        topMoviePanel.Size = new Size(250, 92);
        topMoviePanel.TabIndex = 3;
        topMovieTitleLabel.Font = new Font("Segoe UI", 9.5F);
        topMovieTitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
        topMovieTitleLabel.Location = new Point(18, 16);
        topMovieTitleLabel.Name = "topMovieTitleLabel";
        topMovieTitleLabel.Size = new Size(190, 20);
        topMovieTitleLabel.TabIndex = 0;
        topMovieTitleLabel.Text = "Phim bán chạy";
        topMovieValueLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        topMovieValueLabel.ForeColor = Color.FromArgb(17, 24, 39);
        topMovieValueLabel.Location = new Point(18, 42);
        topMovieValueLabel.Name = "topMovieValueLabel";
        topMovieValueLabel.Size = new Size(210, 34);
        topMovieValueLabel.TabIndex = 1;
        topMovieValueLabel.Text = "Mai";
        bestShowtimePanel.BackColor = Color.White;
        bestShowtimePanel.BorderStyle = BorderStyle.FixedSingle;
        bestShowtimePanel.Controls.Add(bestShowtimeValueLabel);
        bestShowtimePanel.Controls.Add(bestShowtimeTitleLabel);
        bestShowtimePanel.Location = new Point(816, 88);
        bestShowtimePanel.Name = "bestShowtimePanel";
        bestShowtimePanel.Size = new Size(250, 92);
        bestShowtimePanel.TabIndex = 4;
        bestShowtimeTitleLabel.Font = new Font("Segoe UI", 9.5F);
        bestShowtimeTitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
        bestShowtimeTitleLabel.Location = new Point(18, 16);
        bestShowtimeTitleLabel.Name = "bestShowtimeTitleLabel";
        bestShowtimeTitleLabel.Size = new Size(200, 20);
        bestShowtimeTitleLabel.TabIndex = 0;
        bestShowtimeTitleLabel.Text = "Suất chiếu nhiều vé nhất";
        bestShowtimeValueLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        bestShowtimeValueLabel.ForeColor = Color.FromArgb(17, 24, 39);
        bestShowtimeValueLabel.Location = new Point(18, 42);
        bestShowtimeValueLabel.Name = "bestShowtimeValueLabel";
        bestShowtimeValueLabel.Size = new Size(210, 34);
        bestShowtimeValueLabel.TabIndex = 1;
        bestShowtimeValueLabel.Text = "19:30 - Phòng 2";
        // 
        // gridPanel
        // 
        gridPanel.BackColor = Color.White;
        gridPanel.BorderStyle = BorderStyle.FixedSingle;
        gridPanel.Controls.Add(revenueGrid);
        gridPanel.Controls.Add(gridTitleLabel);
        gridPanel.Location = new Point(18, 198);
        gridPanel.Name = "gridPanel";
        gridPanel.Size = new Size(690, 392);
        gridPanel.TabIndex = 5;
        gridTitleLabel.AutoSize = true;
        gridTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        gridTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        gridTitleLabel.Location = new Point(18, 18);
        gridTitleLabel.Name = "gridTitleLabel";
        gridTitleLabel.Size = new Size(158, 21);
        gridTitleLabel.TabIndex = 0;
        gridTitleLabel.Text = "Doanh thu theo phim";
        revenueGrid.AllowUserToAddRows = false;
        revenueGrid.AllowUserToDeleteRows = false;
        revenueGrid.BackgroundColor = Color.White;
        revenueGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        revenueGrid.Columns.AddRange(new DataGridViewColumn[] { colDate, colMovie, colTickets, colRevenue, colPayment });
        revenueGrid.Location = new Point(18, 56);
        revenueGrid.Name = "revenueGrid";
        revenueGrid.ReadOnly = true;
        revenueGrid.RowHeadersVisible = false;
        revenueGrid.Size = new Size(652, 314);
        revenueGrid.TabIndex = 1;
        revenueGrid.Rows.Add("29/05/2026", "Avengers: Endgame", "68", "6.120.000 đ", "Tiền mặt");
        colDate.HeaderText = "Ngày";
        colDate.Name = "colDate";
        colDate.ReadOnly = true;
        colDate.Width = 100;
        colMovie.HeaderText = "Phim";
        colMovie.Name = "colMovie";
        colMovie.ReadOnly = true;
        colMovie.Width = 190;
        colTickets.HeaderText = "Vé";
        colTickets.Name = "colTickets";
        colTickets.ReadOnly = true;
        colTickets.Width = 70;
        colRevenue.HeaderText = "Doanh thu";
        colRevenue.Name = "colRevenue";
        colRevenue.ReadOnly = true;
        colRevenue.Width = 130;
        colPayment.HeaderText = "Thanh toán";
        colPayment.Name = "colPayment";
        colPayment.ReadOnly = true;
        colPayment.Width = 130;
        // 
        // chartPanel
        // 
        chartPanel.BackColor = Color.White;
        chartPanel.BorderStyle = BorderStyle.FixedSingle;
        chartPanel.Controls.Add(barAvengersLabel);
        chartPanel.Controls.Add(barDuneLabel);
        chartPanel.Controls.Add(barMaiLabel);
        chartPanel.Controls.Add(chartTitleLabel);
        chartPanel.Location = new Point(724, 198);
        chartPanel.Name = "chartPanel";
        chartPanel.Size = new Size(342, 392);
        chartPanel.TabIndex = 6;
        chartTitleLabel.AutoSize = true;
        chartTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        chartTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        chartTitleLabel.Location = new Point(18, 18);
        chartTitleLabel.Name = "chartTitleLabel";
        chartTitleLabel.Size = new Size(151, 21);
        chartTitleLabel.TabIndex = 0;
        chartTitleLabel.Text = "Biểu đồ doanh thu";
        barMaiLabel.BackColor = Color.FromArgb(37, 99, 235);
        barMaiLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        barMaiLabel.ForeColor = Color.White;
        barMaiLabel.Location = new Point(28, 76);
        barMaiLabel.Name = "barMaiLabel";
        barMaiLabel.Size = new Size(250, 38);
        barMaiLabel.TabIndex = 1;
        barMaiLabel.Text = "Mai - 6.2 triệu";
        barMaiLabel.TextAlign = ContentAlignment.MiddleLeft;
        barDuneLabel.BackColor = Color.FromArgb(22, 163, 74);
        barDuneLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        barDuneLabel.ForeColor = Color.White;
        barDuneLabel.Location = new Point(28, 136);
        barDuneLabel.Name = "barDuneLabel";
        barDuneLabel.Size = new Size(282, 38);
        barDuneLabel.TabIndex = 2;
        barDuneLabel.Text = "Dune - 7.0 triệu";
        barDuneLabel.TextAlign = ContentAlignment.MiddleLeft;
        barAvengersLabel.BackColor = Color.FromArgb(245, 158, 11);
        barAvengersLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        barAvengersLabel.ForeColor = Color.White;
        barAvengersLabel.Location = new Point(28, 196);
        barAvengersLabel.Name = "barAvengersLabel";
        barAvengersLabel.Size = new Size(244, 38);
        barAvengersLabel.TabIndex = 3;
        barAvengersLabel.Text = "Avengers - 6.1 triệu";
        barAvengersLabel.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // RevenueReportForm
        // 
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(chartPanel);
        Controls.Add(gridPanel);
        Controls.Add(bestShowtimePanel);
        Controls.Add(topMoviePanel);
        Controls.Add(totalTicketPanel);
        Controls.Add(todayRevenuePanel);
        Controls.Add(actionPanel);
        Name = "RevenueReportForm";
        Text = "Thống kê doanh thu";
        Load += RevenueReportForm_Load;
        actionPanel.ResumeLayout(false);
        todayRevenuePanel.ResumeLayout(false);
        totalTicketPanel.ResumeLayout(false);
        topMoviePanel.ResumeLayout(false);
        bestShowtimePanel.ResumeLayout(false);
        gridPanel.ResumeLayout(false);
        gridPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)revenueGrid).EndInit();
        chartPanel.ResumeLayout(false);
        chartPanel.PerformLayout();
        ResumeLayout(false);
    }
}
