namespace CinemaPro.WinForms.DesignFirst.Forms.Admin;

partial class RoomManagementForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel actionPanel = null!;
    private Button addRoomButton = null!;
    private Button editRoomButton = null!;
    private Button createSeatButton = null!;
    private Button maintenanceButton = null!;
    private Panel gridPanel = null!;
    private DataGridView roomGrid = null!;
    private Panel detailPanel = null!;
    private TextBox roomNameTextBox = null!;
    private ComboBox roomTypeComboBox = null!;
    private NumericUpDown rowCountInput = null!;
    private NumericUpDown seatPerRowInput = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null)) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        actionPanel = new Panel();
        addRoomButton = new Button();
        editRoomButton = new Button();
        createSeatButton = new Button();
        maintenanceButton = new Button();
        gridPanel = new Panel();
        roomGrid = new DataGridView();
        detailPanel = new Panel();
        roomNameTextBox = new TextBox();
        roomTypeComboBox = new ComboBox();
        rowCountInput = new NumericUpDown();
        seatPerRowInput = new NumericUpDown();
        var title = new Label();
        var detailTitle = new Label();
        var nameLabel = new Label();
        var typeLabel = new Label();
        var rowLabel = new Label();
        var seatLabel = new Label();
        actionPanel.SuspendLayout();
        gridPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)roomGrid).BeginInit();
        detailPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)rowCountInput).BeginInit();
        ((System.ComponentModel.ISupportInitialize)seatPerRowInput).BeginInit();
        SuspendLayout();
        actionPanel.BackColor = Color.White;
        actionPanel.BorderStyle = BorderStyle.FixedSingle;
        actionPanel.Controls.Add(maintenanceButton);
        actionPanel.Controls.Add(createSeatButton);
        actionPanel.Controls.Add(editRoomButton);
        actionPanel.Controls.Add(addRoomButton);
        actionPanel.Location = new Point(18, 14);
        actionPanel.Size = new Size(1048, 62);
        addRoomButton.BackColor = Color.FromArgb(37, 99, 235);
        addRoomButton.FlatAppearance.BorderSize = 0;
        addRoomButton.FlatStyle = FlatStyle.Flat;
        addRoomButton.ForeColor = Color.White;
        addRoomButton.Location = new Point(18, 16);
        addRoomButton.Size = new Size(120, 32);
        addRoomButton.Text = "Thêm phòng";
        addRoomButton.Click += ActionButton_Click;
        editRoomButton.BackColor = Color.White;
        editRoomButton.FlatStyle = FlatStyle.Flat;
        editRoomButton.Location = new Point(152, 16);
        editRoomButton.Size = new Size(120, 32);
        editRoomButton.Text = "Sửa phòng";
        editRoomButton.Click += ActionButton_Click;
        createSeatButton.BackColor = Color.White;
        createSeatButton.FlatStyle = FlatStyle.Flat;
        createSeatButton.Location = new Point(286, 16);
        createSeatButton.Size = new Size(120, 32);
        createSeatButton.Text = "Tạo ghế";
        createSeatButton.Click += ActionButton_Click;
        maintenanceButton.BackColor = Color.White;
        maintenanceButton.FlatStyle = FlatStyle.Flat;
        maintenanceButton.ForeColor = Color.FromArgb(220, 38, 38);
        maintenanceButton.Location = new Point(420, 16);
        maintenanceButton.Size = new Size(140, 32);
        maintenanceButton.Text = "Bảo trì phòng";
        maintenanceButton.Click += ActionButton_Click;
        gridPanel.BackColor = Color.White;
        gridPanel.BorderStyle = BorderStyle.FixedSingle;
        gridPanel.Controls.Add(roomGrid);
        gridPanel.Controls.Add(title);
        gridPanel.Location = new Point(18, 94);
        gridPanel.Size = new Size(690, 496);
        title.AutoSize = true;
        title.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        title.Location = new Point(18, 18);
        title.Text = "Danh sách phòng chiếu";
        roomGrid.AllowUserToAddRows = false;
        roomGrid.AllowUserToDeleteRows = false;
        roomGrid.BackgroundColor = Color.White;
        roomGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        roomGrid.Columns.Add("colRoomId", "Mã phòng");
        roomGrid.Columns.Add("colRoomName", "Tên phòng");
        roomGrid.Columns.Add("colRoomType", "Loại phòng");
        roomGrid.Columns.Add("colRows", "Số hàng");
        roomGrid.Columns.Add("colSeats", "Ghế/hàng");
        roomGrid.Columns.Add("colStatus", "Trạng thái");
        roomGrid.Location = new Point(18, 56);
        roomGrid.ReadOnly = true;
        roomGrid.RowHeadersVisible = false;
        roomGrid.Size = new Size(652, 420);
        roomGrid.Rows.Add("R001", "Phòng 1", "2D", "6", "8", "Sẵn sàng");
        detailPanel.BackColor = Color.White;
        detailPanel.BorderStyle = BorderStyle.FixedSingle;
        detailPanel.Controls.Add(seatLabel);
        detailPanel.Controls.Add(seatPerRowInput);
        detailPanel.Controls.Add(rowLabel);
        detailPanel.Controls.Add(rowCountInput);
        detailPanel.Controls.Add(typeLabel);
        detailPanel.Controls.Add(roomTypeComboBox);
        detailPanel.Controls.Add(nameLabel);
        detailPanel.Controls.Add(roomNameTextBox);
        detailPanel.Controls.Add(detailTitle);
        detailPanel.Location = new Point(724, 94);
        detailPanel.Size = new Size(342, 496);
        detailTitle.AutoSize = true;
        detailTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        detailTitle.Location = new Point(18, 18);
        detailTitle.Text = "Thông tin phòng";
        nameLabel.Location = new Point(22, 64);
        nameLabel.Text = "Tên phòng";
        roomNameTextBox.Location = new Point(22, 88);
        roomNameTextBox.Size = new Size(290, 23);
        roomNameTextBox.Text = "Phòng 1";
        typeLabel.Location = new Point(22, 130);
        typeLabel.Text = "Loại phòng";
        roomTypeComboBox.Items.AddRange(new object[] { "2D", "3D", "IMAX", "VIP" });
        roomTypeComboBox.Location = new Point(22, 154);
        roomTypeComboBox.Size = new Size(290, 23);
        rowLabel.Location = new Point(22, 196);
        rowLabel.Text = "Số hàng ghế";
        rowCountInput.Location = new Point(22, 220);
        rowCountInput.Value = 6;
        seatLabel.Location = new Point(174, 196);
        seatLabel.Text = "Ghế mỗi hàng";
        seatPerRowInput.Location = new Point(174, 220);
        seatPerRowInput.Value = 8;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(detailPanel);
        Controls.Add(gridPanel);
        Controls.Add(actionPanel);
        Name = "RoomManagementForm";
        Text = "Quản lý phòng chiếu";
        Load += RoomManagementForm_Load;
        actionPanel.ResumeLayout(false);
        gridPanel.ResumeLayout(false);
        gridPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)roomGrid).EndInit();
        detailPanel.ResumeLayout(false);
        detailPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)rowCountInput).EndInit();
        ((System.ComponentModel.ISupportInitialize)seatPerRowInput).EndInit();
        ResumeLayout(false);
    }
}
