namespace CinemaPro.WinForms.DesignFirst.Forms.Admin;

partial class SettingsForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel cinemaInfoPanel = null!;
    private Panel ticketConfigPanel = null!;
    private Panel paymentPanel = null!;
    private Panel systemPanel = null!;
    private TextBox cinemaNameTextBox = null!;
    private TextBox addressTextBox = null!;
    private TextBox hotlineTextBox = null!;
    private CheckBox cashCheckBox = null!;
    private CheckBox vnpayCheckBox = null!;
    private Button saveButton = null!;
    private Button backupButton = null!;
    private Button restoreButton = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null)) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        cinemaInfoPanel = new Panel();
        ticketConfigPanel = new Panel();
        paymentPanel = new Panel();
        systemPanel = new Panel();
        cinemaNameTextBox = new TextBox();
        addressTextBox = new TextBox();
        hotlineTextBox = new TextBox();
        cashCheckBox = new CheckBox();
        vnpayCheckBox = new CheckBox();
        saveButton = new Button();
        backupButton = new Button();
        restoreButton = new Button();
        var title1 = new Label();
        var title2 = new Label();
        var title3 = new Label();
        var title4 = new Label();
        var nameLabel = new Label();
        var addressLabel = new Label();
        var hotlineLabel = new Label();
        var configText = new Label();
        var systemText = new Label();
        cinemaInfoPanel.SuspendLayout();
        ticketConfigPanel.SuspendLayout();
        paymentPanel.SuspendLayout();
        systemPanel.SuspendLayout();
        SuspendLayout();
        cinemaInfoPanel.BackColor = Color.White;
        cinemaInfoPanel.BorderStyle = BorderStyle.FixedSingle;
        cinemaInfoPanel.Controls.Add(hotlineTextBox);
        cinemaInfoPanel.Controls.Add(hotlineLabel);
        cinemaInfoPanel.Controls.Add(addressTextBox);
        cinemaInfoPanel.Controls.Add(addressLabel);
        cinemaInfoPanel.Controls.Add(cinemaNameTextBox);
        cinemaInfoPanel.Controls.Add(nameLabel);
        cinemaInfoPanel.Controls.Add(title1);
        cinemaInfoPanel.Location = new Point(18, 14);
        cinemaInfoPanel.Size = new Size(520, 218);
        title1.AutoSize = true;
        title1.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        title1.Location = new Point(18, 18);
        title1.Text = "Thông tin rạp";
        nameLabel.Location = new Point(22, 58);
        nameLabel.Text = "Tên rạp";
        cinemaNameTextBox.Location = new Point(22, 82);
        cinemaNameTextBox.Size = new Size(460, 23);
        cinemaNameTextBox.Text = "CinemaPro Central";
        addressLabel.Location = new Point(22, 116);
        addressLabel.Text = "Địa chỉ";
        addressTextBox.Location = new Point(22, 140);
        addressTextBox.Size = new Size(460, 23);
        addressTextBox.Text = "Quận 1, TP. Hồ Chí Minh";
        hotlineLabel.Location = new Point(22, 174);
        hotlineLabel.Text = "Hotline";
        hotlineTextBox.Location = new Point(100, 170);
        hotlineTextBox.Size = new Size(180, 23);
        hotlineTextBox.Text = "1900 0000";
        ticketConfigPanel.BackColor = Color.White;
        ticketConfigPanel.BorderStyle = BorderStyle.FixedSingle;
        ticketConfigPanel.Controls.Add(configText);
        ticketConfigPanel.Controls.Add(title2);
        ticketConfigPanel.Location = new Point(556, 14);
        ticketConfigPanel.Size = new Size(510, 218);
        title2.AutoSize = true;
        title2.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        title2.Location = new Point(18, 18);
        title2.Text = "Cấu hình bán vé";
        configText.Font = new Font("Segoe UI", 10F);
        configText.Location = new Point(22, 62);
        configText.Size = new Size(420, 104);
        configText.Text = "Giữ ghế tạm: 05 phút\r\nCho phép đổi phương thức thanh toán: Có\r\nIn vé sau thanh toán: Bật\r\nDữ liệu chỉ mô phỏng trong RAM";
        paymentPanel.BackColor = Color.White;
        paymentPanel.BorderStyle = BorderStyle.FixedSingle;
        paymentPanel.Controls.Add(saveButton);
        paymentPanel.Controls.Add(vnpayCheckBox);
        paymentPanel.Controls.Add(cashCheckBox);
        paymentPanel.Controls.Add(title3);
        paymentPanel.Location = new Point(18, 250);
        paymentPanel.Size = new Size(520, 250);
        title3.AutoSize = true;
        title3.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        title3.Location = new Point(18, 18);
        title3.Text = "Phương thức thanh toán";
        cashCheckBox.Checked = true;
        cashCheckBox.CheckState = CheckState.Checked;
        cashCheckBox.Location = new Point(24, 64);
        cashCheckBox.Size = new Size(240, 28);
        cashCheckBox.Text = "Tiền mặt";
        vnpayCheckBox.Checked = true;
        vnpayCheckBox.CheckState = CheckState.Checked;
        vnpayCheckBox.Location = new Point(24, 100);
        vnpayCheckBox.Size = new Size(240, 28);
        vnpayCheckBox.Text = "VNPAY Sandbox";
        saveButton.BackColor = Color.FromArgb(37, 99, 235);
        saveButton.FlatAppearance.BorderSize = 0;
        saveButton.FlatStyle = FlatStyle.Flat;
        saveButton.ForeColor = Color.White;
        saveButton.Location = new Point(24, 158);
        saveButton.Size = new Size(140, 36);
        saveButton.Text = "Lưu cài đặt";
        saveButton.Click += FakeActionButton_Click;
        systemPanel.BackColor = Color.White;
        systemPanel.BorderStyle = BorderStyle.FixedSingle;
        systemPanel.Controls.Add(restoreButton);
        systemPanel.Controls.Add(backupButton);
        systemPanel.Controls.Add(systemText);
        systemPanel.Controls.Add(title4);
        systemPanel.Location = new Point(556, 250);
        systemPanel.Size = new Size(510, 250);
        title4.AutoSize = true;
        title4.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        title4.Location = new Point(18, 18);
        title4.Text = "Thông tin hệ thống";
        systemText.Font = new Font("Segoe UI", 10F);
        systemText.Location = new Point(22, 62);
        systemText.Size = new Size(420, 70);
        systemText.Text = "CinemaPro DesignFirst\r\nWinForms UI demo\r\nKhông kết nối database/API thật";
        backupButton.BackColor = Color.White;
        backupButton.FlatStyle = FlatStyle.Flat;
        backupButton.Location = new Point(22, 158);
        backupButton.Size = new Size(132, 36);
        backupButton.Text = "Sao lưu fake";
        backupButton.Click += FakeActionButton_Click;
        restoreButton.BackColor = Color.White;
        restoreButton.FlatStyle = FlatStyle.Flat;
        restoreButton.Location = new Point(170, 158);
        restoreButton.Size = new Size(132, 36);
        restoreButton.Text = "Khôi phục fake";
        restoreButton.Click += FakeActionButton_Click;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(systemPanel);
        Controls.Add(paymentPanel);
        Controls.Add(ticketConfigPanel);
        Controls.Add(cinemaInfoPanel);
        Name = "SettingsForm";
        Text = "Cài đặt hệ thống";
        cinemaInfoPanel.ResumeLayout(false);
        cinemaInfoPanel.PerformLayout();
        ticketConfigPanel.ResumeLayout(false);
        ticketConfigPanel.PerformLayout();
        paymentPanel.ResumeLayout(false);
        paymentPanel.PerformLayout();
        systemPanel.ResumeLayout(false);
        systemPanel.PerformLayout();
        ResumeLayout(false);
    }
}
