namespace CinemaPro.WinForms.DesignFirst.Forms.Admin;

partial class ShowtimeManagementForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel inputPanel = null!;
    private ComboBox movieComboBox = null!;
    private ComboBox roomComboBox = null!;
    private DateTimePicker showDatePicker = null!;
    private DateTimePicker startTimePicker = null!;
    private DateTimePicker endTimePicker = null!;
    private TextBox priceTextBox = null!;
    private ComboBox formatComboBox = null!;
    private ComboBox statusComboBox = null!;
    private Button checkConflictButton = null!;
    private Button createButton = null!;
    private Button editButton = null!;
    private Button cancelButton = null!;
    private Panel gridPanel = null!;
    private DataGridView showtimeGrid = null!;
    private Panel detailPanel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null)) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        inputPanel = new Panel();
        movieComboBox = new ComboBox();
        roomComboBox = new ComboBox();
        showDatePicker = new DateTimePicker();
        startTimePicker = new DateTimePicker();
        endTimePicker = new DateTimePicker();
        priceTextBox = new TextBox();
        formatComboBox = new ComboBox();
        statusComboBox = new ComboBox();
        checkConflictButton = new Button();
        createButton = new Button();
        editButton = new Button();
        cancelButton = new Button();
        gridPanel = new Panel();
        showtimeGrid = new DataGridView();
        detailPanel = new Panel();
        var formTitle = new Label();
        var gridTitle = new Label();
        var detailTitle = new Label();
        var detailText = new Label();
        inputPanel.SuspendLayout();
        gridPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)showtimeGrid).BeginInit();
        detailPanel.SuspendLayout();
        SuspendLayout();
        inputPanel.BackColor = Color.White;
        inputPanel.BorderStyle = BorderStyle.FixedSingle;
        inputPanel.Controls.Add(cancelButton);
        inputPanel.Controls.Add(editButton);
        inputPanel.Controls.Add(createButton);
        inputPanel.Controls.Add(checkConflictButton);
        inputPanel.Controls.Add(statusComboBox);
        inputPanel.Controls.Add(formatComboBox);
        inputPanel.Controls.Add(priceTextBox);
        inputPanel.Controls.Add(endTimePicker);
        inputPanel.Controls.Add(startTimePicker);
        inputPanel.Controls.Add(showDatePicker);
        inputPanel.Controls.Add(roomComboBox);
        inputPanel.Controls.Add(movieComboBox);
        inputPanel.Controls.Add(formTitle);
        inputPanel.Location = new Point(18, 14);
        inputPanel.Size = new Size(1048, 110);
        formTitle.AutoSize = true;
        formTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        formTitle.Location = new Point(18, 14);
        formTitle.Text = "Thông tin suất chiếu";
        movieComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        movieComboBox.Location = new Point(18, 50);
        movieComboBox.Size = new Size(190, 23);
        roomComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        roomComboBox.Location = new Point(222, 50);
        roomComboBox.Size = new Size(130, 23);
        showDatePicker.Format = DateTimePickerFormat.Short;
        showDatePicker.Location = new Point(366, 50);
        showDatePicker.Size = new Size(110, 23);
        startTimePicker.Format = DateTimePickerFormat.Time;
        startTimePicker.ShowUpDown = true;
        startTimePicker.Value = DateTime.Today.AddHours(19);
        startTimePicker.Location = new Point(490, 50);
        startTimePicker.Size = new Size(90, 23);
        endTimePicker.Format = DateTimePickerFormat.Time;
        endTimePicker.ShowUpDown = true;
        endTimePicker.Value = DateTime.Today.AddHours(21);
        endTimePicker.Location = new Point(594, 50);
        endTimePicker.Size = new Size(90, 23);
        priceTextBox.Location = new Point(698, 50);
        priceTextBox.Size = new Size(86, 23);
        priceTextBox.Text = "90000";
        formatComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        formatComboBox.Items.AddRange(new object[] { "2D", "3D", "IMAX" });
        formatComboBox.Location = new Point(798, 50);
        formatComboBox.Size = new Size(76, 23);
        statusComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        statusComboBox.Items.AddRange(new object[] { "Đang bán", "Sắp chiếu", "Đã hủy" });
        statusComboBox.Location = new Point(888, 50);
        statusComboBox.Size = new Size(120, 23);
        checkConflictButton.BackColor = Color.White;
        checkConflictButton.FlatStyle = FlatStyle.Flat;
        checkConflictButton.Location = new Point(18, 78);
        checkConflictButton.Size = new Size(138, 28);
        checkConflictButton.Text = "Kiểm tra trùng lịch";
        checkConflictButton.Click += CheckConflictButton_Click;
        createButton.BackColor = Color.FromArgb(37, 99, 235);
        createButton.FlatAppearance.BorderSize = 0;
        createButton.FlatStyle = FlatStyle.Flat;
        createButton.ForeColor = Color.White;
        createButton.Location = new Point(170, 78);
        createButton.Size = new Size(120, 28);
        createButton.Text = "Tạo suất chiếu";
        createButton.Click += ActionButton_Click;
        editButton.BackColor = Color.White;
        editButton.FlatStyle = FlatStyle.Flat;
        editButton.Location = new Point(304, 78);
        editButton.Size = new Size(120, 28);
        editButton.Text = "Sửa suất chiếu";
        editButton.Click += ActionButton_Click;
        cancelButton.BackColor = Color.White;
        cancelButton.FlatStyle = FlatStyle.Flat;
        cancelButton.ForeColor = Color.FromArgb(220, 38, 38);
        cancelButton.Location = new Point(438, 78);
        cancelButton.Size = new Size(120, 28);
        cancelButton.Text = "Hủy suất chiếu";
        cancelButton.Click += ActionButton_Click;
        gridPanel.BackColor = Color.White;
        gridPanel.BorderStyle = BorderStyle.FixedSingle;
        gridPanel.Controls.Add(showtimeGrid);
        gridPanel.Controls.Add(gridTitle);
        gridPanel.Location = new Point(18, 140);
        gridPanel.Size = new Size(730, 450);
        gridTitle.AutoSize = true;
        gridTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        gridTitle.Location = new Point(18, 18);
        gridTitle.Text = "Danh sách lịch chiếu";
        showtimeGrid.AllowUserToAddRows = false;
        showtimeGrid.AllowUserToDeleteRows = false;
        showtimeGrid.BackgroundColor = Color.White;
        showtimeGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        showtimeGrid.Columns.Add("colId", "Mã");
        showtimeGrid.Columns.Add("colMovie", "Phim");
        showtimeGrid.Columns.Add("colRoom", "Phòng");
        showtimeGrid.Columns.Add("colDate", "Ngày");
        showtimeGrid.Columns.Add("colTime", "Giờ");
        showtimeGrid.Columns.Add("colPrice", "Giá vé");
        showtimeGrid.Columns.Add("colStatus", "Trạng thái");
        showtimeGrid.Location = new Point(18, 56);
        showtimeGrid.ReadOnly = true;
        showtimeGrid.RowHeadersVisible = false;
        showtimeGrid.Size = new Size(692, 372);
        showtimeGrid.Rows.Add("SC004", "Avengers: Endgame", "Phòng 2", "29/05/2026", "19:30 - 22:32", "90.000 đ", "Đang bán");
        detailPanel.BackColor = Color.White;
        detailPanel.BorderStyle = BorderStyle.FixedSingle;
        detailPanel.Controls.Add(detailText);
        detailPanel.Controls.Add(detailTitle);
        detailPanel.Location = new Point(764, 140);
        detailPanel.Size = new Size(302, 450);
        detailTitle.AutoSize = true;
        detailTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        detailTitle.Location = new Point(18, 18);
        detailTitle.Text = "Ghi chú vận hành";
        detailText.Font = new Font("Segoe UI", 10F);
        detailText.Location = new Point(20, 60);
        detailText.Size = new Size(260, 160);
        detailText.Text = "Fake rule:\r\nPhòng 1 + giờ bắt đầu 19:00 sẽ báo trùng lịch.\r\n\r\nKhông ghi database, không gọi API thật.";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(detailPanel);
        Controls.Add(gridPanel);
        Controls.Add(inputPanel);
        Name = "ShowtimeManagementForm";
        Text = "Quản lý lịch chiếu";
        Load += ShowtimeManagementForm_Load;
        inputPanel.ResumeLayout(false);
        inputPanel.PerformLayout();
        gridPanel.ResumeLayout(false);
        gridPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)showtimeGrid).EndInit();
        detailPanel.ResumeLayout(false);
        detailPanel.PerformLayout();
        ResumeLayout(false);
    }
}
