namespace CinemaPro.WinForms.DesignFirst.Forms.Admin;

partial class UserManagementForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel actionPanel = null!;
    private Button addButton = null!;
    private Button editButton = null!;
    private Button lockButton = null!;
    private Button refreshButton = null!;
    private Panel gridPanel = null!;
    private DataGridView userGrid = null!;
    private Panel detailPanel = null!;
    private TextBox fullNameTextBox = null!;
    private TextBox usernameTextBox = null!;
    private ComboBox roleComboBox = null!;
    private ComboBox statusComboBox = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null)) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        actionPanel = new Panel();
        addButton = new Button();
        editButton = new Button();
        lockButton = new Button();
        refreshButton = new Button();
        gridPanel = new Panel();
        userGrid = new DataGridView();
        detailPanel = new Panel();
        fullNameTextBox = new TextBox();
        usernameTextBox = new TextBox();
        roleComboBox = new ComboBox();
        statusComboBox = new ComboBox();
        var title = new Label();
        var detailTitle = new Label();
        var nameLabel = new Label();
        var userLabel = new Label();
        var roleLabel = new Label();
        var statusLabel = new Label();
        actionPanel.SuspendLayout();
        gridPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)userGrid).BeginInit();
        detailPanel.SuspendLayout();
        SuspendLayout();
        actionPanel.BackColor = Color.White;
        actionPanel.BorderStyle = BorderStyle.FixedSingle;
        actionPanel.Controls.Add(refreshButton);
        actionPanel.Controls.Add(lockButton);
        actionPanel.Controls.Add(editButton);
        actionPanel.Controls.Add(addButton);
        actionPanel.Location = new Point(18, 14);
        actionPanel.Size = new Size(1048, 62);
        addButton.BackColor = Color.FromArgb(37, 99, 235);
        addButton.FlatAppearance.BorderSize = 0;
        addButton.FlatStyle = FlatStyle.Flat;
        addButton.ForeColor = Color.White;
        addButton.Location = new Point(18, 16);
        addButton.Size = new Size(110, 32);
        addButton.Text = "Thêm";
        addButton.Click += ActionButton_Click;
        editButton.BackColor = Color.White;
        editButton.FlatStyle = FlatStyle.Flat;
        editButton.Location = new Point(144, 16);
        editButton.Size = new Size(110, 32);
        editButton.Text = "Sửa";
        editButton.Click += ActionButton_Click;
        lockButton.BackColor = Color.White;
        lockButton.FlatStyle = FlatStyle.Flat;
        lockButton.ForeColor = Color.FromArgb(220, 38, 38);
        lockButton.Location = new Point(270, 16);
        lockButton.Size = new Size(130, 32);
        lockButton.Text = "Khóa tài khoản";
        lockButton.Click += ActionButton_Click;
        refreshButton.BackColor = Color.White;
        refreshButton.FlatStyle = FlatStyle.Flat;
        refreshButton.Location = new Point(416, 16);
        refreshButton.Size = new Size(110, 32);
        refreshButton.Text = "Làm mới";
        refreshButton.Click += ActionButton_Click;
        gridPanel.BackColor = Color.White;
        gridPanel.BorderStyle = BorderStyle.FixedSingle;
        gridPanel.Controls.Add(userGrid);
        gridPanel.Controls.Add(title);
        gridPanel.Location = new Point(18, 94);
        gridPanel.Size = new Size(690, 496);
        title.AutoSize = true;
        title.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        title.Location = new Point(18, 18);
        title.Text = "Danh sách nhân viên";
        userGrid.AllowUserToAddRows = false;
        userGrid.AllowUserToDeleteRows = false;
        userGrid.BackgroundColor = Color.White;
        userGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        userGrid.Columns.Add("colUserId", "UserId");
        userGrid.Columns.Add("colFullName", "Họ tên");
        userGrid.Columns.Add("colUsername", "Username");
        userGrid.Columns.Add("colRole", "Role");
        userGrid.Columns.Add("colStatus", "Trạng thái");
        userGrid.Location = new Point(18, 56);
        userGrid.ReadOnly = true;
        userGrid.RowHeadersVisible = false;
        userGrid.Size = new Size(652, 420);
        userGrid.Rows.Add("U001", "Nguyễn Văn Quản", "admin", "Admin", "Hoạt động");
        detailPanel.BackColor = Color.White;
        detailPanel.BorderStyle = BorderStyle.FixedSingle;
        detailPanel.Controls.Add(statusLabel);
        detailPanel.Controls.Add(statusComboBox);
        detailPanel.Controls.Add(roleLabel);
        detailPanel.Controls.Add(roleComboBox);
        detailPanel.Controls.Add(userLabel);
        detailPanel.Controls.Add(usernameTextBox);
        detailPanel.Controls.Add(nameLabel);
        detailPanel.Controls.Add(fullNameTextBox);
        detailPanel.Controls.Add(detailTitle);
        detailPanel.Location = new Point(724, 94);
        detailPanel.Size = new Size(342, 496);
        detailTitle.AutoSize = true;
        detailTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        detailTitle.Location = new Point(18, 18);
        detailTitle.Text = "Thông tin nhân viên";
        nameLabel.Location = new Point(22, 64);
        nameLabel.Text = "Họ tên";
        fullNameTextBox.Location = new Point(22, 88);
        fullNameTextBox.Size = new Size(290, 23);
        fullNameTextBox.Text = "Nguyễn Văn Quản";
        userLabel.Location = new Point(22, 128);
        userLabel.Text = "Username";
        usernameTextBox.Location = new Point(22, 152);
        usernameTextBox.Size = new Size(290, 23);
        usernameTextBox.Text = "admin";
        roleLabel.Location = new Point(22, 192);
        roleLabel.Text = "Role";
        roleComboBox.Items.AddRange(new object[] { "Admin", "Staff" });
        roleComboBox.Location = new Point(22, 216);
        roleComboBox.Size = new Size(290, 23);
        statusLabel.Location = new Point(22, 256);
        statusLabel.Text = "Trạng thái";
        statusComboBox.Items.AddRange(new object[] { "Hoạt động", "Tạm khóa" });
        statusComboBox.Location = new Point(22, 280);
        statusComboBox.Size = new Size(290, 23);
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(detailPanel);
        Controls.Add(gridPanel);
        Controls.Add(actionPanel);
        Name = "UserManagementForm";
        Text = "Quản lý nhân viên";
        Load += UserManagementForm_Load;
        actionPanel.ResumeLayout(false);
        gridPanel.ResumeLayout(false);
        gridPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)userGrid).EndInit();
        detailPanel.ResumeLayout(false);
        detailPanel.PerformLayout();
        ResumeLayout(false);
    }
}
