namespace CinemaPro.WinForms.DesignFirst.Forms.Staff;

partial class StaffDashboardForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel todayShowtimePanel = null!;
    private Panel shiftTicketPanel = null!;
    private Panel shiftRevenuePanel = null!;
    private Panel pendingCheckPanel = null!;
    private Label todayShowtimeTitleLabel = null!;
    private Label todayShowtimeValueLabel = null!;
    private Label todayShowtimeNoteLabel = null!;
    private Label shiftTicketTitleLabel = null!;
    private Label shiftTicketValueLabel = null!;
    private Label shiftTicketNoteLabel = null!;
    private Label shiftRevenueTitleLabel = null!;
    private Label shiftRevenueValueLabel = null!;
    private Label shiftRevenueNoteLabel = null!;
    private Label pendingCheckTitleLabel = null!;
    private Label pendingCheckValueLabel = null!;
    private Label pendingCheckNoteLabel = null!;
    private Panel schedulePanel = null!;
    private Label scheduleTitleLabel = null!;
    private DataGridView todayShowtimeGrid = null!;
    private DataGridViewTextBoxColumn colMovie = null!;
    private DataGridViewTextBoxColumn colRoom = null!;
    private DataGridViewTextBoxColumn colTime = null!;
    private DataGridViewTextBoxColumn colPrice = null!;
    private DataGridViewTextBoxColumn colStatus = null!;
    private Panel quickPanel = null!;
    private Label quickTitleLabel = null!;
    private Label quickNoteLabel = null!;
    private Button saleButton = null!;
    private Button checkButton = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        todayShowtimePanel = new Panel();
        todayShowtimeTitleLabel = new Label();
        todayShowtimeValueLabel = new Label();
        todayShowtimeNoteLabel = new Label();
        shiftTicketPanel = new Panel();
        shiftTicketTitleLabel = new Label();
        shiftTicketValueLabel = new Label();
        shiftTicketNoteLabel = new Label();
        shiftRevenuePanel = new Panel();
        shiftRevenueTitleLabel = new Label();
        shiftRevenueValueLabel = new Label();
        shiftRevenueNoteLabel = new Label();
        pendingCheckPanel = new Panel();
        pendingCheckTitleLabel = new Label();
        pendingCheckValueLabel = new Label();
        pendingCheckNoteLabel = new Label();
        schedulePanel = new Panel();
        todayShowtimeGrid = new DataGridView();
        colMovie = new DataGridViewTextBoxColumn();
        colRoom = new DataGridViewTextBoxColumn();
        colTime = new DataGridViewTextBoxColumn();
        colPrice = new DataGridViewTextBoxColumn();
        colStatus = new DataGridViewTextBoxColumn();
        scheduleTitleLabel = new Label();
        quickPanel = new Panel();
        checkButton = new Button();
        saleButton = new Button();
        quickNoteLabel = new Label();
        quickTitleLabel = new Label();
        todayShowtimePanel.SuspendLayout();
        shiftTicketPanel.SuspendLayout();
        shiftRevenuePanel.SuspendLayout();
        pendingCheckPanel.SuspendLayout();
        schedulePanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)todayShowtimeGrid).BeginInit();
        quickPanel.SuspendLayout();
        SuspendLayout();
        // 
        // stat cards
        // 
        todayShowtimePanel.BackColor = Color.White;
        todayShowtimePanel.BorderStyle = BorderStyle.FixedSingle;
        todayShowtimePanel.Controls.Add(todayShowtimeTitleLabel);
        todayShowtimePanel.Controls.Add(todayShowtimeValueLabel);
        todayShowtimePanel.Controls.Add(todayShowtimeNoteLabel);
        todayShowtimePanel.Location = new Point(18, 16);
        todayShowtimePanel.Name = "todayShowtimePanel";
        todayShowtimePanel.Size = new Size(250, 96);
        todayShowtimePanel.TabIndex = 0;
        todayShowtimeTitleLabel.Font = new Font("Segoe UI", 9.5F);
        todayShowtimeTitleLabel.ForeColor = Color.FromArgb(89, 100, 117);
        todayShowtimeTitleLabel.Location = new Point(18, 14);
        todayShowtimeTitleLabel.Name = "todayShowtimeTitleLabel";
        todayShowtimeTitleLabel.Size = new Size(190, 20);
        todayShowtimeTitleLabel.TabIndex = 0;
        todayShowtimeTitleLabel.Text = "Suất chiếu hôm nay";
        todayShowtimeValueLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        todayShowtimeValueLabel.ForeColor = Color.FromArgb(37, 99, 235);
        todayShowtimeValueLabel.Location = new Point(18, 34);
        todayShowtimeValueLabel.Name = "todayShowtimeValueLabel";
        todayShowtimeValueLabel.Size = new Size(120, 40);
        todayShowtimeValueLabel.TabIndex = 1;
        todayShowtimeValueLabel.Text = "4";
        todayShowtimeNoteLabel.Font = new Font("Segoe UI", 9F);
        todayShowtimeNoteLabel.ForeColor = Color.FromArgb(100, 116, 139);
        todayShowtimeNoteLabel.Location = new Point(18, 74);
        todayShowtimeNoteLabel.Name = "todayShowtimeNoteLabel";
        todayShowtimeNoteLabel.Size = new Size(200, 18);
        todayShowtimeNoteLabel.TabIndex = 2;
        todayShowtimeNoteLabel.Text = "Đang mở bán";
        shiftTicketPanel.BackColor = Color.White;
        shiftTicketPanel.BorderStyle = BorderStyle.FixedSingle;
        shiftTicketPanel.Controls.Add(shiftTicketTitleLabel);
        shiftTicketPanel.Controls.Add(shiftTicketValueLabel);
        shiftTicketPanel.Controls.Add(shiftTicketNoteLabel);
        shiftTicketPanel.Location = new Point(284, 16);
        shiftTicketPanel.Name = "shiftTicketPanel";
        shiftTicketPanel.Size = new Size(250, 96);
        shiftTicketPanel.TabIndex = 1;
        shiftTicketTitleLabel.Font = new Font("Segoe UI", 9.5F);
        shiftTicketTitleLabel.ForeColor = Color.FromArgb(89, 100, 117);
        shiftTicketTitleLabel.Location = new Point(18, 14);
        shiftTicketTitleLabel.Name = "shiftTicketTitleLabel";
        shiftTicketTitleLabel.Size = new Size(190, 20);
        shiftTicketTitleLabel.TabIndex = 0;
        shiftTicketTitleLabel.Text = "Vé đã bán trong ca";
        shiftTicketValueLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        shiftTicketValueLabel.ForeColor = Color.FromArgb(22, 163, 74);
        shiftTicketValueLabel.Location = new Point(18, 34);
        shiftTicketValueLabel.Name = "shiftTicketValueLabel";
        shiftTicketValueLabel.Size = new Size(120, 40);
        shiftTicketValueLabel.TabIndex = 1;
        shiftTicketValueLabel.Text = "4";
        shiftTicketNoteLabel.Font = new Font("Segoe UI", 9F);
        shiftTicketNoteLabel.ForeColor = Color.FromArgb(100, 116, 139);
        shiftTicketNoteLabel.Location = new Point(18, 74);
        shiftTicketNoteLabel.Name = "shiftTicketNoteLabel";
        shiftTicketNoteLabel.Size = new Size(200, 18);
        shiftTicketNoteLabel.TabIndex = 2;
        shiftTicketNoteLabel.Text = "Tính trong phiên demo";
        shiftRevenuePanel.BackColor = Color.White;
        shiftRevenuePanel.BorderStyle = BorderStyle.FixedSingle;
        shiftRevenuePanel.Controls.Add(shiftRevenueTitleLabel);
        shiftRevenuePanel.Controls.Add(shiftRevenueValueLabel);
        shiftRevenuePanel.Controls.Add(shiftRevenueNoteLabel);
        shiftRevenuePanel.Location = new Point(550, 16);
        shiftRevenuePanel.Name = "shiftRevenuePanel";
        shiftRevenuePanel.Size = new Size(250, 96);
        shiftRevenuePanel.TabIndex = 2;
        shiftRevenueTitleLabel.Font = new Font("Segoe UI", 9.5F);
        shiftRevenueTitleLabel.ForeColor = Color.FromArgb(89, 100, 117);
        shiftRevenueTitleLabel.Location = new Point(18, 14);
        shiftRevenueTitleLabel.Name = "shiftRevenueTitleLabel";
        shiftRevenueTitleLabel.Size = new Size(190, 20);
        shiftRevenueTitleLabel.TabIndex = 0;
        shiftRevenueTitleLabel.Text = "Doanh thu trong ca";
        shiftRevenueValueLabel.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        shiftRevenueValueLabel.ForeColor = Color.FromArgb(37, 99, 235);
        shiftRevenueValueLabel.Location = new Point(18, 39);
        shiftRevenueValueLabel.Name = "shiftRevenueValueLabel";
        shiftRevenueValueLabel.Size = new Size(210, 30);
        shiftRevenueValueLabel.TabIndex = 1;
        shiftRevenueValueLabel.Text = "585.000 đ";
        shiftRevenueNoteLabel.Font = new Font("Segoe UI", 9F);
        shiftRevenueNoteLabel.ForeColor = Color.FromArgb(100, 116, 139);
        shiftRevenueNoteLabel.Location = new Point(18, 74);
        shiftRevenueNoteLabel.Name = "shiftRevenueNoteLabel";
        shiftRevenueNoteLabel.Size = new Size(200, 18);
        shiftRevenueNoteLabel.TabIndex = 2;
        shiftRevenueNoteLabel.Text = "Chưa bao gồm hoàn vé";
        pendingCheckPanel.BackColor = Color.White;
        pendingCheckPanel.BorderStyle = BorderStyle.FixedSingle;
        pendingCheckPanel.Controls.Add(pendingCheckTitleLabel);
        pendingCheckPanel.Controls.Add(pendingCheckValueLabel);
        pendingCheckPanel.Controls.Add(pendingCheckNoteLabel);
        pendingCheckPanel.Location = new Point(816, 16);
        pendingCheckPanel.Name = "pendingCheckPanel";
        pendingCheckPanel.Size = new Size(250, 96);
        pendingCheckPanel.TabIndex = 3;
        pendingCheckTitleLabel.Font = new Font("Segoe UI", 9.5F);
        pendingCheckTitleLabel.ForeColor = Color.FromArgb(89, 100, 117);
        pendingCheckTitleLabel.Location = new Point(18, 14);
        pendingCheckTitleLabel.Name = "pendingCheckTitleLabel";
        pendingCheckTitleLabel.Size = new Size(190, 20);
        pendingCheckTitleLabel.TabIndex = 0;
        pendingCheckTitleLabel.Text = "Vé chờ kiểm tra";
        pendingCheckValueLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        pendingCheckValueLabel.ForeColor = Color.FromArgb(245, 158, 11);
        pendingCheckValueLabel.Location = new Point(18, 34);
        pendingCheckValueLabel.Name = "pendingCheckValueLabel";
        pendingCheckValueLabel.Size = new Size(120, 40);
        pendingCheckValueLabel.TabIndex = 1;
        pendingCheckValueLabel.Text = "2";
        pendingCheckNoteLabel.Font = new Font("Segoe UI", 9F);
        pendingCheckNoteLabel.ForeColor = Color.FromArgb(100, 116, 139);
        pendingCheckNoteLabel.Location = new Point(18, 74);
        pendingCheckNoteLabel.Name = "pendingCheckNoteLabel";
        pendingCheckNoteLabel.Size = new Size(200, 18);
        pendingCheckNoteLabel.TabIndex = 2;
        pendingCheckNoteLabel.Text = "Trạng thái chưa sử dụng";
        // 
        // schedulePanel
        // 
        schedulePanel.BackColor = Color.White;
        schedulePanel.BorderStyle = BorderStyle.FixedSingle;
        schedulePanel.Controls.Add(todayShowtimeGrid);
        schedulePanel.Controls.Add(scheduleTitleLabel);
        schedulePanel.Location = new Point(18, 130);
        schedulePanel.Name = "schedulePanel";
        schedulePanel.Size = new Size(710, 454);
        schedulePanel.TabIndex = 4;
        scheduleTitleLabel.AutoSize = true;
        scheduleTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        scheduleTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        scheduleTitleLabel.Location = new Point(18, 18);
        scheduleTitleLabel.Name = "scheduleTitleLabel";
        scheduleTitleLabel.Size = new Size(156, 21);
        scheduleTitleLabel.TabIndex = 0;
        scheduleTitleLabel.Text = "Lịch chiếu hôm nay";
        todayShowtimeGrid.AllowUserToAddRows = false;
        todayShowtimeGrid.AllowUserToDeleteRows = false;
        todayShowtimeGrid.BackgroundColor = Color.White;
        todayShowtimeGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        todayShowtimeGrid.Columns.AddRange(new DataGridViewColumn[] { colMovie, colRoom, colTime, colPrice, colStatus });
        todayShowtimeGrid.Location = new Point(18, 58);
        todayShowtimeGrid.Name = "todayShowtimeGrid";
        todayShowtimeGrid.ReadOnly = true;
        todayShowtimeGrid.RowHeadersVisible = false;
        todayShowtimeGrid.Size = new Size(672, 374);
        todayShowtimeGrid.TabIndex = 1;
        todayShowtimeGrid.Rows.Add("Avengers: Endgame", "Phòng 2", "19:30 - 22:32", "90.000 đ", "Đang bán");
        todayShowtimeGrid.Rows.Add("Dune: Part Two", "IMAX 1", "14:00 - 16:46", "130.000 đ", "Đang bán");
        colMovie.HeaderText = "Phim";
        colMovie.Name = "colMovie";
        colMovie.ReadOnly = true;
        colMovie.Width = 210;
        colRoom.HeaderText = "Phòng";
        colRoom.Name = "colRoom";
        colRoom.ReadOnly = true;
        colRoom.Width = 90;
        colTime.HeaderText = "Giờ";
        colTime.Name = "colTime";
        colTime.ReadOnly = true;
        colTime.Width = 120;
        colPrice.HeaderText = "Giá";
        colPrice.Name = "colPrice";
        colPrice.ReadOnly = true;
        colStatus.HeaderText = "Trạng thái";
        colStatus.Name = "colStatus";
        colStatus.ReadOnly = true;
        // 
        // quickPanel
        // 
        quickPanel.BackColor = Color.White;
        quickPanel.BorderStyle = BorderStyle.FixedSingle;
        quickPanel.Controls.Add(checkButton);
        quickPanel.Controls.Add(saleButton);
        quickPanel.Controls.Add(quickNoteLabel);
        quickPanel.Controls.Add(quickTitleLabel);
        quickPanel.Location = new Point(744, 130);
        quickPanel.Name = "quickPanel";
        quickPanel.Size = new Size(322, 454);
        quickPanel.TabIndex = 5;
        quickTitleLabel.AutoSize = true;
        quickTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        quickTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        quickTitleLabel.Location = new Point(22, 22);
        quickTitleLabel.Name = "quickTitleLabel";
        quickTitleLabel.Size = new Size(111, 21);
        quickTitleLabel.TabIndex = 0;
        quickTitleLabel.Text = "Thao tác nhanh";
        quickNoteLabel.Font = new Font("Segoe UI", 10F);
        quickNoteLabel.ForeColor = Color.FromArgb(89, 100, 117);
        quickNoteLabel.Location = new Point(22, 60);
        quickNoteLabel.Name = "quickNoteLabel";
        quickNoteLabel.Size = new Size(260, 68);
        quickNoteLabel.TabIndex = 1;
        quickNoteLabel.Text = "Chọn nhanh nghiệp vụ quầy vé thường dùng trong ca làm việc.";
        saleButton.BackColor = Color.FromArgb(37, 99, 235);
        saleButton.FlatAppearance.BorderSize = 0;
        saleButton.FlatStyle = FlatStyle.Flat;
        saleButton.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        saleButton.ForeColor = Color.White;
        saleButton.Location = new Point(22, 158);
        saleButton.Name = "saleButton";
        saleButton.Size = new Size(270, 48);
        saleButton.TabIndex = 2;
        saleButton.Text = "Bán vé";
        saleButton.UseVisualStyleBackColor = false;
        saleButton.Click += SaleButton_Click;
        checkButton.BackColor = Color.White;
        checkButton.FlatStyle = FlatStyle.Flat;
        checkButton.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        checkButton.ForeColor = Color.FromArgb(37, 99, 235);
        checkButton.Location = new Point(22, 224);
        checkButton.Name = "checkButton";
        checkButton.Size = new Size(270, 48);
        checkButton.TabIndex = 3;
        checkButton.Text = "Kiểm tra vé";
        checkButton.UseVisualStyleBackColor = false;
        checkButton.Click += CheckButton_Click;
        // 
        // StaffDashboardForm
        // 
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(quickPanel);
        Controls.Add(schedulePanel);
        Controls.Add(pendingCheckPanel);
        Controls.Add(shiftRevenuePanel);
        Controls.Add(shiftTicketPanel);
        Controls.Add(todayShowtimePanel);
        Name = "StaffDashboardForm";
        Text = "Dashboard nhân viên";
        Load += StaffDashboardForm_Load;
        todayShowtimePanel.ResumeLayout(false);
        shiftTicketPanel.ResumeLayout(false);
        shiftRevenuePanel.ResumeLayout(false);
        pendingCheckPanel.ResumeLayout(false);
        schedulePanel.ResumeLayout(false);
        schedulePanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)todayShowtimeGrid).EndInit();
        quickPanel.ResumeLayout(false);
        quickPanel.PerformLayout();
        ResumeLayout(false);
    }
}
