namespace CinemaPro.WinForms.DesignFirst.Forms.Staff;

partial class TicketSaleForm
{
    private System.ComponentModel.IContainer components = null!;
    private Panel filterPanel = null!;
    private Label movieFilterLabel = null!;
    private ComboBox movieComboBox = null!;
    private Label showtimeFilterLabel = null!;
    private ComboBox showtimeComboBox = null!;
    private Panel infoPanel = null!;
    private Label infoTitleLabel = null!;
    private Label movieTitleLabel = null!;
    private Label movieTitleValueLabel = null!;
    private Label roomLabel = null!;
    private Label roomValueLabel = null!;
    private Label formatLabel = null!;
    private Label formatValueLabel = null!;
    private Label priceLabel = null!;
    private Label priceValueLabel = null!;
    private Panel seatSectionPanel = null!;
    private Label seatSectionTitleLabel = null!;
    private Panel seatMapPanel = null!;
    private Label designerScreenLabel = null!;
    private Label designerSeatHintLabel = null!;
    private Label legendAvailableLabel = null!;
    private Label legendSelectedLabel = null!;
    private Label legendSoldLabel = null!;
    private Label legendMaintenanceLabel = null!;
    private Panel orderPanel = null!;
    private Label orderTitleLabel = null!;
    private Label selectedCountLabel = null!;
    private ListBox selectedSeatListBox = null!;
    private Label paymentMethodLabel = null!;
    private ComboBox paymentMethodComboBox = null!;
    private Label totalCaptionLabel = null!;
    private Label totalValueLabel = null!;
    private Button paymentButton = null!;
    private Button clearButton = null!;
    private Panel recentPanel = null!;
    private Label recentTitleLabel = null!;
    private DataGridView recentTicketsGrid = null!;
    private DataGridViewTextBoxColumn colTicketCode = null!;
    private DataGridViewTextBoxColumn colTicketMovie = null!;
    private DataGridViewTextBoxColumn colTicketSeats = null!;
    private DataGridViewTextBoxColumn colTicketAmount = null!;
    private DataGridViewTextBoxColumn colTicketStatus = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        filterPanel = new Panel();
        movieFilterLabel = new Label();
        movieComboBox = new ComboBox();
        showtimeFilterLabel = new Label();
        showtimeComboBox = new ComboBox();
        infoPanel = new Panel();
        priceValueLabel = new Label();
        priceLabel = new Label();
        formatValueLabel = new Label();
        formatLabel = new Label();
        roomValueLabel = new Label();
        roomLabel = new Label();
        movieTitleValueLabel = new Label();
        movieTitleLabel = new Label();
        infoTitleLabel = new Label();
        seatSectionPanel = new Panel();
        legendMaintenanceLabel = new Label();
        legendSoldLabel = new Label();
        legendSelectedLabel = new Label();
        legendAvailableLabel = new Label();
        seatMapPanel = new Panel();
        designerSeatHintLabel = new Label();
        designerScreenLabel = new Label();
        seatSectionTitleLabel = new Label();
        orderPanel = new Panel();
        clearButton = new Button();
        paymentButton = new Button();
        totalValueLabel = new Label();
        totalCaptionLabel = new Label();
        paymentMethodComboBox = new ComboBox();
        paymentMethodLabel = new Label();
        selectedSeatListBox = new ListBox();
        selectedCountLabel = new Label();
        orderTitleLabel = new Label();
        recentPanel = new Panel();
        recentTicketsGrid = new DataGridView();
        colTicketCode = new DataGridViewTextBoxColumn();
        colTicketMovie = new DataGridViewTextBoxColumn();
        colTicketSeats = new DataGridViewTextBoxColumn();
        colTicketAmount = new DataGridViewTextBoxColumn();
        colTicketStatus = new DataGridViewTextBoxColumn();
        recentTitleLabel = new Label();
        filterPanel.SuspendLayout();
        infoPanel.SuspendLayout();
        seatSectionPanel.SuspendLayout();
        seatMapPanel.SuspendLayout();
        orderPanel.SuspendLayout();
        recentPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)recentTicketsGrid).BeginInit();
        SuspendLayout();
        // 
        // filterPanel
        // 
        filterPanel.BackColor = Color.White;
        filterPanel.BorderStyle = BorderStyle.FixedSingle;
        filterPanel.Controls.Add(showtimeComboBox);
        filterPanel.Controls.Add(showtimeFilterLabel);
        filterPanel.Controls.Add(movieComboBox);
        filterPanel.Controls.Add(movieFilterLabel);
        filterPanel.Location = new Point(18, 14);
        filterPanel.Name = "filterPanel";
        filterPanel.Size = new Size(1048, 68);
        filterPanel.TabIndex = 0;
        movieFilterLabel.AutoSize = true;
        movieFilterLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        movieFilterLabel.ForeColor = Color.FromArgb(17, 24, 39);
        movieFilterLabel.Location = new Point(18, 14);
        movieFilterLabel.Name = "movieFilterLabel";
        movieFilterLabel.Size = new Size(70, 15);
        movieFilterLabel.TabIndex = 0;
        movieFilterLabel.Text = "Chọn phim";
        movieComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        movieComboBox.Font = new Font("Segoe UI", 10F);
        movieComboBox.FormattingEnabled = true;
        movieComboBox.Items.AddRange(new object[] { "Avengers: Endgame", "Mai", "Dune: Part Two" });
        movieComboBox.Location = new Point(18, 32);
        movieComboBox.Name = "movieComboBox";
        movieComboBox.Size = new Size(420, 25);
        movieComboBox.TabIndex = 1;
        movieComboBox.SelectedIndexChanged += MovieComboBox_SelectedIndexChanged;
        showtimeFilterLabel.AutoSize = true;
        showtimeFilterLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        showtimeFilterLabel.ForeColor = Color.FromArgb(17, 24, 39);
        showtimeFilterLabel.Location = new Point(470, 14);
        showtimeFilterLabel.Name = "showtimeFilterLabel";
        showtimeFilterLabel.Size = new Size(91, 15);
        showtimeFilterLabel.TabIndex = 2;
        showtimeFilterLabel.Text = "Chọn suất chiếu";
        showtimeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        showtimeComboBox.Font = new Font("Segoe UI", 10F);
        showtimeComboBox.FormattingEnabled = true;
        showtimeComboBox.Items.AddRange(new object[] { "19:30 - 22:32 | Phòng 2 | 3D" });
        showtimeComboBox.Location = new Point(470, 32);
        showtimeComboBox.Name = "showtimeComboBox";
        showtimeComboBox.Size = new Size(420, 25);
        showtimeComboBox.TabIndex = 3;
        showtimeComboBox.SelectedIndexChanged += ShowtimeComboBox_SelectedIndexChanged;
        // 
        // infoPanel
        // 
        infoPanel.BackColor = Color.White;
        infoPanel.BorderStyle = BorderStyle.FixedSingle;
        infoPanel.Controls.Add(priceValueLabel);
        infoPanel.Controls.Add(priceLabel);
        infoPanel.Controls.Add(formatValueLabel);
        infoPanel.Controls.Add(formatLabel);
        infoPanel.Controls.Add(roomValueLabel);
        infoPanel.Controls.Add(roomLabel);
        infoPanel.Controls.Add(movieTitleValueLabel);
        infoPanel.Controls.Add(movieTitleLabel);
        infoPanel.Controls.Add(infoTitleLabel);
        infoPanel.Location = new Point(18, 96);
        infoPanel.Name = "infoPanel";
        infoPanel.Size = new Size(240, 338);
        infoPanel.TabIndex = 1;
        infoTitleLabel.AutoSize = true;
        infoTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        infoTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        infoTitleLabel.Location = new Point(18, 18);
        infoTitleLabel.Name = "infoTitleLabel";
        infoTitleLabel.Size = new Size(112, 21);
        infoTitleLabel.TabIndex = 0;
        infoTitleLabel.Text = "Thông tin vé";
        movieTitleLabel.AutoSize = true;
        movieTitleLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        movieTitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
        movieTitleLabel.Location = new Point(18, 62);
        movieTitleLabel.Name = "movieTitleLabel";
        movieTitleLabel.Size = new Size(35, 15);
        movieTitleLabel.TabIndex = 1;
        movieTitleLabel.Text = "Phim";
        movieTitleValueLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        movieTitleValueLabel.ForeColor = Color.FromArgb(17, 24, 39);
        movieTitleValueLabel.Location = new Point(18, 82);
        movieTitleValueLabel.Name = "movieTitleValueLabel";
        movieTitleValueLabel.Size = new Size(198, 42);
        movieTitleValueLabel.TabIndex = 2;
        movieTitleValueLabel.Text = "Avengers: Endgame";
        roomLabel.AutoSize = true;
        roomLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        roomLabel.ForeColor = Color.FromArgb(100, 116, 139);
        roomLabel.Location = new Point(18, 136);
        roomLabel.Name = "roomLabel";
        roomLabel.Size = new Size(43, 15);
        roomLabel.TabIndex = 3;
        roomLabel.Text = "Phòng";
        roomValueLabel.Font = new Font("Segoe UI", 10F);
        roomValueLabel.ForeColor = Color.FromArgb(17, 24, 39);
        roomValueLabel.Location = new Point(18, 156);
        roomValueLabel.Name = "roomValueLabel";
        roomValueLabel.Size = new Size(198, 24);
        roomValueLabel.TabIndex = 4;
        roomValueLabel.Text = "Phòng 2";
        formatLabel.AutoSize = true;
        formatLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        formatLabel.ForeColor = Color.FromArgb(100, 116, 139);
        formatLabel.Location = new Point(18, 198);
        formatLabel.Name = "formatLabel";
        formatLabel.Size = new Size(65, 15);
        formatLabel.TabIndex = 5;
        formatLabel.Text = "Định dạng";
        formatValueLabel.Font = new Font("Segoe UI", 10F);
        formatValueLabel.ForeColor = Color.FromArgb(17, 24, 39);
        formatValueLabel.Location = new Point(18, 218);
        formatValueLabel.Name = "formatValueLabel";
        formatValueLabel.Size = new Size(198, 24);
        formatValueLabel.TabIndex = 6;
        formatValueLabel.Text = "3D";
        priceLabel.AutoSize = true;
        priceLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        priceLabel.ForeColor = Color.FromArgb(100, 116, 139);
        priceLabel.Location = new Point(18, 260);
        priceLabel.Name = "priceLabel";
        priceLabel.Size = new Size(41, 15);
        priceLabel.TabIndex = 7;
        priceLabel.Text = "Giá vé";
        priceValueLabel.Font = new Font("Segoe UI", 13F, FontStyle.Bold);
        priceValueLabel.ForeColor = Color.FromArgb(37, 99, 235);
        priceValueLabel.Location = new Point(18, 280);
        priceValueLabel.Name = "priceValueLabel";
        priceValueLabel.Size = new Size(198, 30);
        priceValueLabel.TabIndex = 8;
        priceValueLabel.Text = "90.000 đ";
        // 
        // seatSectionPanel
        // 
        seatSectionPanel.BackColor = Color.White;
        seatSectionPanel.BorderStyle = BorderStyle.FixedSingle;
        seatSectionPanel.Controls.Add(legendMaintenanceLabel);
        seatSectionPanel.Controls.Add(legendSoldLabel);
        seatSectionPanel.Controls.Add(legendSelectedLabel);
        seatSectionPanel.Controls.Add(legendAvailableLabel);
        seatSectionPanel.Controls.Add(seatMapPanel);
        seatSectionPanel.Controls.Add(seatSectionTitleLabel);
        seatSectionPanel.Location = new Point(276, 96);
        seatSectionPanel.Name = "seatSectionPanel";
        seatSectionPanel.Size = new Size(520, 338);
        seatSectionPanel.TabIndex = 2;
        seatSectionTitleLabel.AutoSize = true;
        seatSectionTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        seatSectionTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        seatSectionTitleLabel.Location = new Point(18, 18);
        seatSectionTitleLabel.Name = "seatSectionTitleLabel";
        seatSectionTitleLabel.Size = new Size(86, 21);
        seatSectionTitleLabel.TabIndex = 0;
        seatSectionTitleLabel.Text = "Sơ đồ ghế";
        seatMapPanel.BackColor = Color.FromArgb(248, 250, 252);
        seatMapPanel.BorderStyle = BorderStyle.FixedSingle;
        seatMapPanel.Controls.Add(designerSeatHintLabel);
        seatMapPanel.Controls.Add(designerScreenLabel);
        seatMapPanel.Location = new Point(18, 52);
        seatMapPanel.Name = "seatMapPanel";
        seatMapPanel.Size = new Size(480, 224);
        seatMapPanel.TabIndex = 1;
        designerScreenLabel.BackColor = Color.FromArgb(226, 232, 240);
        designerScreenLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        designerScreenLabel.ForeColor = Color.FromArgb(71, 85, 105);
        designerScreenLabel.Location = new Point(62, 14);
        designerScreenLabel.Name = "designerScreenLabel";
        designerScreenLabel.Size = new Size(350, 28);
        designerScreenLabel.TabIndex = 0;
        designerScreenLabel.Text = "MÀN HÌNH";
        designerScreenLabel.TextAlign = ContentAlignment.MiddleCenter;
        designerSeatHintLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        designerSeatHintLabel.ForeColor = Color.FromArgb(100, 116, 139);
        designerSeatHintLabel.Location = new Point(70, 82);
        designerSeatHintLabel.Name = "designerSeatHintLabel";
        designerSeatHintLabel.Size = new Size(340, 68);
        designerSeatHintLabel.TabIndex = 1;
        designerSeatHintLabel.Text = "Ghế sẽ được render theo phòng chiếu khi chạy app\r\nA1  A2  A3  A4  A5  A6  A7  A8";
        designerSeatHintLabel.TextAlign = ContentAlignment.MiddleCenter;
        legendAvailableLabel.BackColor = Color.White;
        legendAvailableLabel.BorderStyle = BorderStyle.FixedSingle;
        legendAvailableLabel.Font = new Font("Segoe UI", 8.5F);
        legendAvailableLabel.Location = new Point(18, 292);
        legendAvailableLabel.Name = "legendAvailableLabel";
        legendAvailableLabel.Size = new Size(96, 24);
        legendAvailableLabel.TabIndex = 2;
        legendAvailableLabel.Text = "Trống";
        legendAvailableLabel.TextAlign = ContentAlignment.MiddleCenter;
        legendSelectedLabel.BackColor = Color.FromArgb(37, 99, 235);
        legendSelectedLabel.Font = new Font("Segoe UI", 8.5F);
        legendSelectedLabel.ForeColor = Color.White;
        legendSelectedLabel.Location = new Point(126, 292);
        legendSelectedLabel.Name = "legendSelectedLabel";
        legendSelectedLabel.Size = new Size(96, 24);
        legendSelectedLabel.TabIndex = 3;
        legendSelectedLabel.Text = "Đang chọn";
        legendSelectedLabel.TextAlign = ContentAlignment.MiddleCenter;
        legendSoldLabel.BackColor = Color.FromArgb(220, 38, 38);
        legendSoldLabel.Font = new Font("Segoe UI", 8.5F);
        legendSoldLabel.ForeColor = Color.White;
        legendSoldLabel.Location = new Point(234, 292);
        legendSoldLabel.Name = "legendSoldLabel";
        legendSoldLabel.Size = new Size(96, 24);
        legendSoldLabel.TabIndex = 4;
        legendSoldLabel.Text = "Đã bán";
        legendSoldLabel.TextAlign = ContentAlignment.MiddleCenter;
        legendMaintenanceLabel.BackColor = Color.FromArgb(148, 163, 184);
        legendMaintenanceLabel.Font = new Font("Segoe UI", 8.5F);
        legendMaintenanceLabel.ForeColor = Color.White;
        legendMaintenanceLabel.Location = new Point(342, 292);
        legendMaintenanceLabel.Name = "legendMaintenanceLabel";
        legendMaintenanceLabel.Size = new Size(96, 24);
        legendMaintenanceLabel.TabIndex = 5;
        legendMaintenanceLabel.Text = "Bảo trì";
        legendMaintenanceLabel.TextAlign = ContentAlignment.MiddleCenter;
        // 
        // orderPanel
        // 
        orderPanel.BackColor = Color.White;
        orderPanel.BorderStyle = BorderStyle.FixedSingle;
        orderPanel.Controls.Add(clearButton);
        orderPanel.Controls.Add(paymentButton);
        orderPanel.Controls.Add(totalValueLabel);
        orderPanel.Controls.Add(totalCaptionLabel);
        orderPanel.Controls.Add(paymentMethodComboBox);
        orderPanel.Controls.Add(paymentMethodLabel);
        orderPanel.Controls.Add(selectedSeatListBox);
        orderPanel.Controls.Add(selectedCountLabel);
        orderPanel.Controls.Add(orderTitleLabel);
        orderPanel.Location = new Point(814, 96);
        orderPanel.Name = "orderPanel";
        orderPanel.Size = new Size(252, 338);
        orderPanel.TabIndex = 3;
        orderTitleLabel.AutoSize = true;
        orderTitleLabel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        orderTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        orderTitleLabel.Location = new Point(18, 18);
        orderTitleLabel.Name = "orderTitleLabel";
        orderTitleLabel.Size = new Size(92, 21);
        orderTitleLabel.TabIndex = 0;
        orderTitleLabel.Text = "Đặt vé";
        selectedCountLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        selectedCountLabel.ForeColor = Color.FromArgb(37, 99, 235);
        selectedCountLabel.Location = new Point(154, 21);
        selectedCountLabel.Name = "selectedCountLabel";
        selectedCountLabel.Size = new Size(76, 20);
        selectedCountLabel.TabIndex = 1;
        selectedCountLabel.Text = "0 ghế";
        selectedCountLabel.TextAlign = ContentAlignment.MiddleRight;
        selectedSeatListBox.Font = new Font("Segoe UI", 10F);
        selectedSeatListBox.FormattingEnabled = true;
        selectedSeatListBox.ItemHeight = 17;
        selectedSeatListBox.Items.AddRange(new object[] { "B6", "B7" });
        selectedSeatListBox.Location = new Point(18, 54);
        selectedSeatListBox.Name = "selectedSeatListBox";
        selectedSeatListBox.Size = new Size(212, 89);
        selectedSeatListBox.TabIndex = 2;
        paymentMethodLabel.AutoSize = true;
        paymentMethodLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        paymentMethodLabel.ForeColor = Color.FromArgb(100, 116, 139);
        paymentMethodLabel.Location = new Point(18, 160);
        paymentMethodLabel.Name = "paymentMethodLabel";
        paymentMethodLabel.Size = new Size(128, 15);
        paymentMethodLabel.TabIndex = 3;
        paymentMethodLabel.Text = "Phương thức thanh toán";
        paymentMethodComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        paymentMethodComboBox.Font = new Font("Segoe UI", 10F);
        paymentMethodComboBox.FormattingEnabled = true;
        paymentMethodComboBox.Items.AddRange(new object[] { "Tiền mặt", "VNPAY Sandbox" });
        paymentMethodComboBox.Location = new Point(18, 182);
        paymentMethodComboBox.Name = "paymentMethodComboBox";
        paymentMethodComboBox.Size = new Size(212, 25);
        paymentMethodComboBox.TabIndex = 4;
        totalCaptionLabel.AutoSize = true;
        totalCaptionLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        totalCaptionLabel.ForeColor = Color.FromArgb(100, 116, 139);
        totalCaptionLabel.Location = new Point(18, 222);
        totalCaptionLabel.Name = "totalCaptionLabel";
        totalCaptionLabel.Size = new Size(59, 15);
        totalCaptionLabel.TabIndex = 5;
        totalCaptionLabel.Text = "Tổng tiền";
        totalValueLabel.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        totalValueLabel.ForeColor = Color.FromArgb(37, 99, 235);
        totalValueLabel.Location = new Point(18, 240);
        totalValueLabel.Name = "totalValueLabel";
        totalValueLabel.Size = new Size(212, 34);
        totalValueLabel.TabIndex = 6;
        totalValueLabel.Text = "0 đ";
        paymentButton.BackColor = Color.FromArgb(37, 99, 235);
        paymentButton.FlatAppearance.BorderSize = 0;
        paymentButton.FlatStyle = FlatStyle.Flat;
        paymentButton.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        paymentButton.ForeColor = Color.White;
        paymentButton.Location = new Point(18, 284);
        paymentButton.Name = "paymentButton";
        paymentButton.Size = new Size(132, 36);
        paymentButton.TabIndex = 7;
        paymentButton.Text = "Thanh toán";
        paymentButton.UseVisualStyleBackColor = false;
        paymentButton.Click += PaymentButton_Click;
        clearButton.BackColor = Color.White;
        clearButton.FlatStyle = FlatStyle.Flat;
        clearButton.Font = new Font("Segoe UI", 9F);
        clearButton.ForeColor = Color.FromArgb(17, 24, 39);
        clearButton.Location = new Point(158, 284);
        clearButton.Name = "clearButton";
        clearButton.Size = new Size(72, 36);
        clearButton.TabIndex = 8;
        clearButton.Text = "Hủy";
        clearButton.UseVisualStyleBackColor = false;
        clearButton.Click += ClearButton_Click;
        // 
        // recentPanel
        // 
        recentPanel.BackColor = Color.White;
        recentPanel.BorderStyle = BorderStyle.FixedSingle;
        recentPanel.Controls.Add(recentTicketsGrid);
        recentPanel.Controls.Add(recentTitleLabel);
        recentPanel.Location = new Point(18, 450);
        recentPanel.Name = "recentPanel";
        recentPanel.Size = new Size(1048, 140);
        recentPanel.TabIndex = 4;
        recentTitleLabel.AutoSize = true;
        recentTitleLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        recentTitleLabel.ForeColor = Color.FromArgb(17, 24, 39);
        recentTitleLabel.Location = new Point(18, 12);
        recentTitleLabel.Name = "recentTitleLabel";
        recentTitleLabel.Size = new Size(133, 20);
        recentTitleLabel.TabIndex = 0;
        recentTitleLabel.Text = "Giao dịch gần đây";
        recentTicketsGrid.AllowUserToAddRows = false;
        recentTicketsGrid.AllowUserToDeleteRows = false;
        recentTicketsGrid.BackgroundColor = Color.White;
        recentTicketsGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        recentTicketsGrid.Columns.AddRange(new DataGridViewColumn[] { colTicketCode, colTicketMovie, colTicketSeats, colTicketAmount, colTicketStatus });
        recentTicketsGrid.Location = new Point(18, 40);
        recentTicketsGrid.Name = "recentTicketsGrid";
        recentTicketsGrid.ReadOnly = true;
        recentTicketsGrid.RowHeadersVisible = false;
        recentTicketsGrid.Size = new Size(1010, 82);
        recentTicketsGrid.TabIndex = 1;
        recentTicketsGrid.Rows.Add("TK000001", "Avengers: Endgame", "B6", "90.000 đ", "Chưa sử dụng");
        colTicketCode.HeaderText = "Mã vé";
        colTicketCode.Name = "colTicketCode";
        colTicketCode.ReadOnly = true;
        colTicketCode.Width = 120;
        colTicketMovie.HeaderText = "Phim";
        colTicketMovie.Name = "colTicketMovie";
        colTicketMovie.ReadOnly = true;
        colTicketMovie.Width = 250;
        colTicketSeats.HeaderText = "Ghế";
        colTicketSeats.Name = "colTicketSeats";
        colTicketSeats.ReadOnly = true;
        colTicketAmount.HeaderText = "Tổng tiền";
        colTicketAmount.Name = "colTicketAmount";
        colTicketAmount.ReadOnly = true;
        colTicketStatus.HeaderText = "Trạng thái";
        colTicketStatus.Name = "colTicketStatus";
        colTicketStatus.ReadOnly = true;
        // 
        // TicketSaleForm
        // 
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 251);
        ClientSize = new Size(1084, 606);
        Controls.Add(recentPanel);
        Controls.Add(orderPanel);
        Controls.Add(seatSectionPanel);
        Controls.Add(infoPanel);
        Controls.Add(filterPanel);
        Name = "TicketSaleForm";
        Text = "Bán vé";
        Load += TicketSaleForm_Load;
        filterPanel.ResumeLayout(false);
        filterPanel.PerformLayout();
        infoPanel.ResumeLayout(false);
        infoPanel.PerformLayout();
        seatSectionPanel.ResumeLayout(false);
        seatSectionPanel.PerformLayout();
        seatMapPanel.ResumeLayout(false);
        orderPanel.ResumeLayout(false);
        orderPanel.PerformLayout();
        recentPanel.ResumeLayout(false);
        recentPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)recentTicketsGrid).EndInit();
        ResumeLayout(false);
    }
}
